### ISSUE TITLE
마이페이지 컴포넌트 제작

### ISSUE THREAD

**Issue by ning1315** [codestates/bsg-client#10]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 마이페이지 컴포넌트 제작
2. [x] 현재 나의 정보 표시
3. [x] 회원정보 수정 btn
4. [x] 회원 탈퇴 btn

### Estimated time
> Pick one
### Labels
- Estimated time: `1H`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency:  `Low`
