### ISSUE TITLE
댓글 컴포넌트 작성

### ISSUE THREAD

**Issue by ning1315** [codestates/bsg-client#21]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: comment
- Member:`JunSeok`, `SangCheul`
### TODO
1. [x] 해당글의 댓글 리스트 출력
2. [x] 댓글 입력창
3. [x] 댓글 보내기 btn
4. [ ] 댓글 삭제 btn

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`

- Urgency: `Middle`
**Additional context**
